### ISSUE TITLE
Nice work！

### ISSUE THREAD

**Issue by ANZHIQIANG** [xuarehere/yolo_series_deepsort_pytorch#10]
It ran easily on my device,thanks for your work!

**Comment by software93** [comment]
hello dear ??? 
which python version did you use?
this repo can work only on linux or windowse too?

**Comment by xuarehere** [comment]
> hello dear ??? which python version did you use? this repo can work only on linux or windowse too?

hello, thank you focusing on this project.
I develop the project on linux, and the python version is 3.8.6
