### ISSUE TITLE
Problem about Deepsort training

### ISSUE THREAD

**Issue by PiBigStar5712** [xuarehere/yolo_series_deepsort_pytorch#11]
I wanted to train my own data set, and it wasn't about pedestrians or cars. So far I've trained the object detection part of YOLO, but how do I train the reID part of deepsort.

**Comment by xuarehere** [comment]
Please see the readme carefully

**Comment by PiBigStar5712** [comment]
> Please see the readme carefully

I certainly know to run the train.py file to train it. I mean, how do I make a data set for training ReID?

**Comment by xuarehere** [comment]
You can check out the instructions in this section yourself.([link](https://github.com/xuarehere/yolo_series_deepsort_pytorch/issues/5))
Additionally, you can make your own tracking datasets based on existing data (e.g., Market-1501 format, VeRi format).
